apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pubsub-producer
  name: pubsub-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub-producer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pubsub-producer
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "pubsub-producer"
        # dapr.io/app-port: "3050"    
    spec:
      containers:
      - image: k3d-registry.localhost:5000/pubsub-producer
        name: pubsub-producer
        resources: 
          requests:
            memory: "500Mi"
          limits:
            memory: "700Mi"
status: {}

---


apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pubsub-producer-service
  name: pubsub-producer-service
spec:
  ports:
  - name: 8084-8084
    port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: pubsub-producer-service
  type: ClusterIP
status:
  loadBalancer: {}
