apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: new-subscription
spec:
  topic: testingtopic
  route: /
  pubsubname: messagebus
# scopes:
# - fabrikam-functions
# - dapr-consumer
# - kafka-function
